# Generated by Django 3.2.8 on 2021-10-23 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211023_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='habits',
            field=models.ManyToManyField(blank=True, related_name='articles_contained_in', to='api.Habit'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.habit'),
        ),
        migrations.DeleteModel(
            name='HabitMet',
        ),
        migrations.AddField(
            model_name='goalday',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_days', to='api.goal'),
        ),
    ]
