# Generated by Django 3.2.8 on 2021-10-23 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_habit_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='amount_saved_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
