# Generated by Django 3.2.8 on 2021-10-24 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_habit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='owner',
            field=models.ForeignKey(blank=True, default='e5973dcd-588f-4a4b-a962-87d5d611e20d', on_delete=django.db.models.deletion.CASCADE, related_name='article', to='api.user'),
            preserve_default=False,
        ),
    ]
