# Generated by Django 3.2.8 on 2021-10-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211024_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='api.articlegroup'),
        ),
    ]
