# Generated by Django 3.2.8 on 2021-10-24 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_article_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlegroup',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_groups_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
